<option value="/2015_VSC_Plots/AberavonAberavon_VS2015_pie.png">Aberavon
<option value="/2015_VSC_Plots/AberconwyAberavon_VS2015_pie.png">Aberconwy
<option value="/2015_VSC_Plots/Aberdeen NorthAberavon_VS2015_pie.png">Aberdeen North
<option value="/2015_VSC_Plots/Aberdeen SouthAberavon_VS2015_pie.png">Aberdeen South
<option value="/2015_VSC_Plots/Aberdeenshire West & KincardineAberavon_VS2015_pie.png">Aberdeenshire West & Kincardine
<option value="/2015_VSC_Plots/Airdrie & ShottsAberavon_VS2015_pie.png">Airdrie & Shotts
<option value="/2015_VSC_Plots/AldershotAberavon_VS2015_pie.png">Aldershot
<option value="/2015_VSC_Plots/Aldridge-BrownhillsAberavon_VS2015_pie.png">Aldridge-Brownhills
<option value="/2015_VSC_Plots/Altrincham & Sale WestAberavon_VS2015_pie.png">Altrincham & Sale West
<option value="/2015_VSC_Plots/Alyn & DeesideAberavon_VS2015_pie.png">Alyn & Deeside
<option value="/2015_VSC_Plots/Amber ValleyAberavon_VS2015_pie.png">Amber Valley
<option value="/2015_VSC_Plots/AngusAberavon_VS2015_pie.png">Angus
<option value="/2015_VSC_Plots/Antrim EastAberavon_VS2015_pie.png">Antrim East
<option value="/2015_VSC_Plots/Antrim NorthAberavon_VS2015_pie.png">Antrim North
<option value="/2015_VSC_Plots/Antrim SouthAberavon_VS2015_pie.png">Antrim South
<option value="/2015_VSC_Plots/ArfonAberavon_VS2015_pie.png">Arfon
<option value="/2015_VSC_Plots/Argyll & ButeAberavon_VS2015_pie.png">Argyll & Bute
<option value="/2015_VSC_Plots/Arundel & South DownsAberavon_VS2015_pie.png">Arundel & South Downs
<option value="/2015_VSC_Plots/AshfieldAberavon_VS2015_pie.png">Ashfield
<option value="/2015_VSC_Plots/AshfordAberavon_VS2015_pie.png">Ashford
<option value="/2015_VSC_Plots/Ashton Under LyneAberavon_VS2015_pie.png">Ashton Under Lyne
<option value="/2015_VSC_Plots/AylesburyAberavon_VS2015_pie.png">Aylesbury
<option value="/2015_VSC_Plots/Ayr, Carrick & CumnockAberavon_VS2015_pie.png">Ayr, Carrick & Cumnock"
<option value="/2015_VSC_Plots/Ayrshire CentralAberavon_VS2015_pie.png">Ayrshire Central
<option value="/2015_VSC_Plots/Ayrshire North & ArranAberavon_VS2015_pie.png">Ayrshire North & Arran
<option value="/2015_VSC_Plots/BanburyAberavon_VS2015_pie.png">Banbury
<option value="/2015_VSC_Plots/Banff & BuchanAberavon_VS2015_pie.png">Banff & Buchan
<option value="/2015_VSC_Plots/BarkingAberavon_VS2015_pie.png">Barking
<option value="/2015_VSC_Plots/Barnsley CentralAberavon_VS2015_pie.png">Barnsley Central
<option value="/2015_VSC_Plots/Barnsley EastAberavon_VS2015_pie.png">Barnsley East
<option value="/2015_VSC_Plots/Barrow & FurnessAberavon_VS2015_pie.png">Barrow & Furness
<option value="/2015_VSC_Plots/Basildon & BillericayAberavon_VS2015_pie.png">Basildon & Billericay
<option value="/2015_VSC_Plots/Basildon South & Thurrock EastAberavon_VS2015_pie.png">Basildon South & Thurrock East
<option value="/2015_VSC_Plots/BasingstokeAberavon_VS2015_pie.png">Basingstoke
<option value="/2015_VSC_Plots/BassetlawAberavon_VS2015_pie.png">Bassetlaw
<option value="/2015_VSC_Plots/BathAberavon_VS2015_pie.png">Bath
<option value="/2015_VSC_Plots/Batley & SpenAberavon_VS2015_pie.png">Batley & Spen
<option value="/2015_VSC_Plots/BatterseaAberavon_VS2015_pie.png">Battersea
<option value="/2015_VSC_Plots/BeaconsfieldAberavon_VS2015_pie.png">Beaconsfield
<option value="/2015_VSC_Plots/BeckenhamAberavon_VS2015_pie.png">Beckenham
<option value="/2015_VSC_Plots/BedfordAberavon_VS2015_pie.png">Bedford
<option value="/2015_VSC_Plots/Bedfordshire MidAberavon_VS2015_pie.png">Bedfordshire Mid
<option value="/2015_VSC_Plots/Bedfordshire North EastAberavon_VS2015_pie.png">Bedfordshire North East
<option value="/2015_VSC_Plots/Bedfordshire South WestAberavon_VS2015_pie.png">Bedfordshire South West
<option value="/2015_VSC_Plots/Belfast EastAberavon_VS2015_pie.png">Belfast East
<option value="/2015_VSC_Plots/Belfast NorthAberavon_VS2015_pie.png">Belfast North
<option value="/2015_VSC_Plots/Belfast SouthAberavon_VS2015_pie.png">Belfast South
<option value="/2015_VSC_Plots/Belfast WestAberavon_VS2015_pie.png">Belfast West
<option value="/2015_VSC_Plots/Bermondsey & Old SouthwarkAberavon_VS2015_pie.png">Bermondsey & Old Southwark
<option value="/2015_VSC_Plots/Berwick-Upon-TweedAberavon_VS2015_pie.png">Berwick-Upon-Tweed
<option value="/2015_VSC_Plots/Berwickshire, Roxburgh & SelkirkAberavon_VS2015_pie.png">Berwickshire, Roxburgh & Selkirk"
<option value="/2015_VSC_Plots/Bethnal Green & BowAberavon_VS2015_pie.png">Bethnal Green & Bow
<option value="/2015_VSC_Plots/Beverley & HoldernessAberavon_VS2015_pie.png">Beverley & Holderness
<option value="/2015_VSC_Plots/Bexhill & BattleAberavon_VS2015_pie.png">Bexhill & Battle
<option value="/2015_VSC_Plots/Bexleyheath & CrayfordAberavon_VS2015_pie.png">Bexleyheath & Crayford
<option value="/2015_VSC_Plots/BirkenheadAberavon_VS2015_pie.png">Birkenhead
<option value="/2015_VSC_Plots/Birmingham EdgbastonAberavon_VS2015_pie.png">Birmingham Edgbaston
<option value="/2015_VSC_Plots/Birmingham ErdingtonAberavon_VS2015_pie.png">Birmingham Erdington
<option value="/2015_VSC_Plots/Birmingham Hall GreenAberavon_VS2015_pie.png">Birmingham Hall Green
<option value="/2015_VSC_Plots/Birmingham Hodge HillAberavon_VS2015_pie.png">Birmingham Hodge Hill
<option value="/2015_VSC_Plots/Birmingham LadywoodAberavon_VS2015_pie.png">Birmingham Ladywood
<option value="/2015_VSC_Plots/Birmingham NorthfieldAberavon_VS2015_pie.png">Birmingham Northfield
<option value="/2015_VSC_Plots/Birmingham Perry BarrAberavon_VS2015_pie.png">Birmingham Perry Barr
<option value="/2015_VSC_Plots/Birmingham Selly OakAberavon_VS2015_pie.png">Birmingham Selly Oak
<option value="/2015_VSC_Plots/Birmingham YardleyAberavon_VS2015_pie.png">Birmingham Yardley
<option value="/2015_VSC_Plots/Bishop AucklandAberavon_VS2015_pie.png">Bishop Auckland
<option value="/2015_VSC_Plots/BlackburnAberavon_VS2015_pie.png">Blackburn
<option value="/2015_VSC_Plots/Blackley & BroughtonAberavon_VS2015_pie.png">Blackley & Broughton
<option value="/2015_VSC_Plots/Blackpool North & CleveleysAberavon_VS2015_pie.png">Blackpool North & Cleveleys
<option value="/2015_VSC_Plots/Blackpool SouthAberavon_VS2015_pie.png">Blackpool South
<option value="/2015_VSC_Plots/Blaenau GwentAberavon_VS2015_pie.png">Blaenau Gwent
<option value="/2015_VSC_Plots/BlaydonAberavon_VS2015_pie.png">Blaydon
<option value="/2015_VSC_Plots/Blyth ValleyAberavon_VS2015_pie.png">Blyth Valley
<option value="/2015_VSC_Plots/Bognor Regis & LittlehamptonAberavon_VS2015_pie.png">Bognor Regis & Littlehampton
<option value="/2015_VSC_Plots/BolsoverAberavon_VS2015_pie.png">Bolsover
<option value="/2015_VSC_Plots/Bolton North EastAberavon_VS2015_pie.png">Bolton North East
<option value="/2015_VSC_Plots/Bolton South EastAberavon_VS2015_pie.png">Bolton South East
<option value="/2015_VSC_Plots/Bolton WestAberavon_VS2015_pie.png">Bolton West
<option value="/2015_VSC_Plots/BootleAberavon_VS2015_pie.png">Bootle
<option value="/2015_VSC_Plots/Boston & SkegnessAberavon_VS2015_pie.png">Boston & Skegness
<option value="/2015_VSC_Plots/BosworthAberavon_VS2015_pie.png">Bosworth
<option value="/2015_VSC_Plots/Bournemouth EastAberavon_VS2015_pie.png">Bournemouth East
<option value="/2015_VSC_Plots/Bournemouth WestAberavon_VS2015_pie.png">Bournemouth West
<option value="/2015_VSC_Plots/BracknellAberavon_VS2015_pie.png">Bracknell
<option value="/2015_VSC_Plots/Bradford EastAberavon_VS2015_pie.png">Bradford East
<option value="/2015_VSC_Plots/Bradford SouthAberavon_VS2015_pie.png">Bradford South
<option value="/2015_VSC_Plots/Bradford WestAberavon_VS2015_pie.png">Bradford West
<option value="/2015_VSC_Plots/BraintreeAberavon_VS2015_pie.png">Braintree
<option value="/2015_VSC_Plots/Brecon & RadnorshireAberavon_VS2015_pie.png">Brecon & Radnorshire
<option value="/2015_VSC_Plots/Brent CentralAberavon_VS2015_pie.png">Brent Central
<option value="/2015_VSC_Plots/Brent NorthAberavon_VS2015_pie.png">Brent North
<option value="/2015_VSC_Plots/Brentford & IsleworthAberavon_VS2015_pie.png">Brentford & Isleworth
<option value="/2015_VSC_Plots/Brentwood & OngarAberavon_VS2015_pie.png">Brentwood & Ongar
<option value="/2015_VSC_Plots/BridgendAberavon_VS2015_pie.png">Bridgend
<option value="/2015_VSC_Plots/Bridgwater & Somerset WestAberavon_VS2015_pie.png">Bridgwater & Somerset West
<option value="/2015_VSC_Plots/Brigg & GooleAberavon_VS2015_pie.png">Brigg & Goole
<option value="/2015_VSC_Plots/Brighton KemptownAberavon_VS2015_pie.png">Brighton Kemptown
<option value="/2015_VSC_Plots/Brighton PavilionAberavon_VS2015_pie.png">Brighton Pavilion
<option value="/2015_VSC_Plots/Bristol EastAberavon_VS2015_pie.png">Bristol East
<option value="/2015_VSC_Plots/Bristol North WestAberavon_VS2015_pie.png">Bristol North West
<option value="/2015_VSC_Plots/Bristol SouthAberavon_VS2015_pie.png">Bristol South
<option value="/2015_VSC_Plots/Bristol WestAberavon_VS2015_pie.png">Bristol West
<option value="/2015_VSC_Plots/BroadlandAberavon_VS2015_pie.png">Broadland
<option value="/2015_VSC_Plots/Bromley & ChislehurstAberavon_VS2015_pie.png">Bromley & Chislehurst
<option value="/2015_VSC_Plots/BromsgroveAberavon_VS2015_pie.png">Bromsgrove
<option value="/2015_VSC_Plots/BroxbourneAberavon_VS2015_pie.png">Broxbourne
<option value="/2015_VSC_Plots/BroxtoweAberavon_VS2015_pie.png">Broxtowe
<option value="/2015_VSC_Plots/BuckinghamAberavon_VS2015_pie.png">Buckingham
<option value="/2015_VSC_Plots/BurnleyAberavon_VS2015_pie.png">Burnley
<option value="/2015_VSC_Plots/BurtonAberavon_VS2015_pie.png">Burton
<option value="/2015_VSC_Plots/Bury NorthAberavon_VS2015_pie.png">Bury North
<option value="/2015_VSC_Plots/Bury SouthAberavon_VS2015_pie.png">Bury South
<option value="/2015_VSC_Plots/Bury St EdmundsAberavon_VS2015_pie.png">Bury St Edmunds
<option value="/2015_VSC_Plots/CaerphillyAberavon_VS2015_pie.png">Caerphilly
<option value="/2015_VSC_Plots/Caithness, Sutherland & Easter RossAberavon_VS2015_pie.png">Caithness, Sutherland & Easter Ross"
<option value="/2015_VSC_Plots/Calder ValleyAberavon_VS2015_pie.png">Calder Valley
<option value="/2015_VSC_Plots/Camberwell & PeckhamAberavon_VS2015_pie.png">Camberwell & Peckham
<option value="/2015_VSC_Plots/Camborne & RedruthAberavon_VS2015_pie.png">Camborne & Redruth
<option value="/2015_VSC_Plots/CambridgeAberavon_VS2015_pie.png">Cambridge
<option value="/2015_VSC_Plots/Cambridgeshire North EastAberavon_VS2015_pie.png">Cambridgeshire North East
<option value="/2015_VSC_Plots/Cambridgeshire North WestAberavon_VS2015_pie.png">Cambridgeshire North West
<option value="/2015_VSC_Plots/Cambridgeshire SouthAberavon_VS2015_pie.png">Cambridgeshire South
<option value="/2015_VSC_Plots/Cambridgeshire South EastAberavon_VS2015_pie.png">Cambridgeshire South East
<option value="/2015_VSC_Plots/Cannock ChaseAberavon_VS2015_pie.png">Cannock Chase
<option value="/2015_VSC_Plots/CanterburyAberavon_VS2015_pie.png">Canterbury
<option value="/2015_VSC_Plots/Cardiff CentralAberavon_VS2015_pie.png">Cardiff Central
<option value="/2015_VSC_Plots/Cardiff NorthAberavon_VS2015_pie.png">Cardiff North
<option value="/2015_VSC_Plots/Cardiff South & PenarthAberavon_VS2015_pie.png">Cardiff South & Penarth
<option value="/2015_VSC_Plots/Cardiff WestAberavon_VS2015_pie.png">Cardiff West
<option value="/2015_VSC_Plots/CarlisleAberavon_VS2015_pie.png">Carlisle
<option value="/2015_VSC_Plots/Carmarthen East & DinefwrAberavon_VS2015_pie.png">Carmarthen East & Dinefwr
<option value="/2015_VSC_Plots/Carmarthen West & Pembrokeshire SouthAberavon_VS2015_pie.png">Carmarthen West & Pembrokeshire South
<option value="/2015_VSC_Plots/Carshalton & WallingtonAberavon_VS2015_pie.png">Carshalton & Wallington
<option value="/2015_VSC_Plots/Castle PointAberavon_VS2015_pie.png">Castle Point
<option value="/2015_VSC_Plots/CeredigionAberavon_VS2015_pie.png">Ceredigion
<option value="/2015_VSC_Plots/CharnwoodAberavon_VS2015_pie.png">Charnwood
<option value="/2015_VSC_Plots/Chatham & AylesfordAberavon_VS2015_pie.png">Chatham & Aylesford
<option value="/2015_VSC_Plots/CheadleAberavon_VS2015_pie.png">Cheadle
<option value="/2015_VSC_Plots/ChelmsfordAberavon_VS2015_pie.png">Chelmsford
<option value="/2015_VSC_Plots/Chelsea & FulhamAberavon_VS2015_pie.png">Chelsea & Fulham
<option value="/2015_VSC_Plots/CheltenhamAberavon_VS2015_pie.png">Cheltenham
<option value="/2015_VSC_Plots/Chesham & AmershamAberavon_VS2015_pie.png">Chesham & Amersham
<option value="/2015_VSC_Plots/Chester, City OfAberavon_VS2015_pie.png">Chester, City Of"
<option value="/2015_VSC_Plots/ChesterfieldAberavon_VS2015_pie.png">Chesterfield
<option value="/2015_VSC_Plots/ChichesterAberavon_VS2015_pie.png">Chichester
<option value="/2015_VSC_Plots/Chingford & Woodford GreenAberavon_VS2015_pie.png">Chingford & Woodford Green
<option value="/2015_VSC_Plots/ChippenhamAberavon_VS2015_pie.png">Chippenham
<option value="/2015_VSC_Plots/Chipping BarnetAberavon_VS2015_pie.png">Chipping Barnet
<option value="/2015_VSC_Plots/ChorleyAberavon_VS2015_pie.png">Chorley
<option value="/2015_VSC_Plots/ChristchurchAberavon_VS2015_pie.png">Christchurch
<option value="/2015_VSC_Plots/Cities Of London & WestminsterAberavon_VS2015_pie.png">Cities Of London & Westminster
<option value="/2015_VSC_Plots/ClactonAberavon_VS2015_pie.png">Clacton
<option value="/2015_VSC_Plots/CleethorpesAberavon_VS2015_pie.png">Cleethorpes
<option value="/2015_VSC_Plots/Clwyd SouthAberavon_VS2015_pie.png">Clwyd South
<option value="/2015_VSC_Plots/Clwyd WestAberavon_VS2015_pie.png">Clwyd West
<option value="/2015_VSC_Plots/Coatbridge, Chryston & BellshillAberavon_VS2015_pie.png">Coatbridge, Chryston & Bellshill"
<option value="/2015_VSC_Plots/ColchesterAberavon_VS2015_pie.png">Colchester
<option value="/2015_VSC_Plots/Colne ValleyAberavon_VS2015_pie.png">Colne Valley
<option value="/2015_VSC_Plots/CongletonAberavon_VS2015_pie.png">Congleton
<option value="/2015_VSC_Plots/CopelandAberavon_VS2015_pie.png">Copeland
<option value="/2015_VSC_Plots/CorbyAberavon_VS2015_pie.png">Corby
<option value="/2015_VSC_Plots/Cornwall NorthAberavon_VS2015_pie.png">Cornwall North
<option value="/2015_VSC_Plots/Cornwall South EastAberavon_VS2015_pie.png">Cornwall South East
<option value="/2015_VSC_Plots/Cotswolds, TheAberavon_VS2015_pie.png">Cotswolds, The"
<option value="/2015_VSC_Plots/Coventry North EastAberavon_VS2015_pie.png">Coventry North East
<option value="/2015_VSC_Plots/Coventry North WestAberavon_VS2015_pie.png">Coventry North West
<option value="/2015_VSC_Plots/Coventry SouthAberavon_VS2015_pie.png">Coventry South
<option value="/2015_VSC_Plots/CrawleyAberavon_VS2015_pie.png">Crawley
<option value="/2015_VSC_Plots/Crewe & NantwichAberavon_VS2015_pie.png">Crewe & Nantwich
<option value="/2015_VSC_Plots/Croydon CentralAberavon_VS2015_pie.png">Croydon Central
<option value="/2015_VSC_Plots/Croydon NorthAberavon_VS2015_pie.png">Croydon North
<option value="/2015_VSC_Plots/Croydon SouthAberavon_VS2015_pie.png">Croydon South
<option value="/2015_VSC_Plots/Cumbernauld, Kilsyth & Kirkintilloch EastAberavon_VS2015_pie.png">Cumbernauld, Kilsyth & Kirkintilloch East"
<option value="/2015_VSC_Plots/Cynon ValleyAberavon_VS2015_pie.png">Cynon Valley
<option value="/2015_VSC_Plots/Dagenham & RainhamAberavon_VS2015_pie.png">Dagenham & Rainham
<option value="/2015_VSC_Plots/DarlingtonAberavon_VS2015_pie.png">Darlington
<option value="/2015_VSC_Plots/DartfordAberavon_VS2015_pie.png">Dartford
<option value="/2015_VSC_Plots/DaventryAberavon_VS2015_pie.png">Daventry
<option value="/2015_VSC_Plots/DelynAberavon_VS2015_pie.png">Delyn
<option value="/2015_VSC_Plots/Denton & ReddishAberavon_VS2015_pie.png">Denton & Reddish
<option value="/2015_VSC_Plots/Derby NorthAberavon_VS2015_pie.png">Derby North
<option value="/2015_VSC_Plots/Derby SouthAberavon_VS2015_pie.png">Derby South
<option value="/2015_VSC_Plots/Derbyshire DalesAberavon_VS2015_pie.png">Derbyshire Dales
<option value="/2015_VSC_Plots/Derbyshire MidAberavon_VS2015_pie.png">Derbyshire Mid
<option value="/2015_VSC_Plots/Derbyshire North EastAberavon_VS2015_pie.png">Derbyshire North East
<option value="/2015_VSC_Plots/Derbyshire SouthAberavon_VS2015_pie.png">Derbyshire South
<option value="/2015_VSC_Plots/DevizesAberavon_VS2015_pie.png">Devizes
<option value="/2015_VSC_Plots/Devon CentralAberavon_VS2015_pie.png">Devon Central
<option value="/2015_VSC_Plots/Devon EastAberavon_VS2015_pie.png">Devon East
<option value="/2015_VSC_Plots/Devon NorthAberavon_VS2015_pie.png">Devon North
<option value="/2015_VSC_Plots/Devon South WestAberavon_VS2015_pie.png">Devon South West
<option value="/2015_VSC_Plots/Devon West & TorridgeAberavon_VS2015_pie.png">Devon West & Torridge
<option value="/2015_VSC_Plots/DewsburyAberavon_VS2015_pie.png">Dewsbury
<option value="/2015_VSC_Plots/Don ValleyAberavon_VS2015_pie.png">Don Valley
<option value="/2015_VSC_Plots/Doncaster CentralAberavon_VS2015_pie.png">Doncaster Central
<option value="/2015_VSC_Plots/Doncaster NorthAberavon_VS2015_pie.png">Doncaster North
<option value="/2015_VSC_Plots/Dorset Mid & Poole NorthAberavon_VS2015_pie.png">Dorset Mid & Poole North
<option value="/2015_VSC_Plots/Dorset NorthAberavon_VS2015_pie.png">Dorset North
<option value="/2015_VSC_Plots/Dorset SouthAberavon_VS2015_pie.png">Dorset South
<option value="/2015_VSC_Plots/Dorset WestAberavon_VS2015_pie.png">Dorset West
<option value="/2015_VSC_Plots/DoverAberavon_VS2015_pie.png">Dover
<option value="/2015_VSC_Plots/Down NorthAberavon_VS2015_pie.png">Down North
<option value="/2015_VSC_Plots/Down SouthAberavon_VS2015_pie.png">Down South
<option value="/2015_VSC_Plots/Dudley NorthAberavon_VS2015_pie.png">Dudley North
<option value="/2015_VSC_Plots/Dudley SouthAberavon_VS2015_pie.png">Dudley South
<option value="/2015_VSC_Plots/Dulwich & West NorwoodAberavon_VS2015_pie.png">Dulwich & West Norwood
<option value="/2015_VSC_Plots/Dumfries & GallowayAberavon_VS2015_pie.png">Dumfries & Galloway
<option value="/2015_VSC_Plots/Dumfriesshire, Clydesdale & TweeddaleAberavon_VS2015_pie.png">Dumfriesshire, Clydesdale & Tweeddale"
<option value="/2015_VSC_Plots/Dunbartonshire EastAberavon_VS2015_pie.png">Dunbartonshire East
<option value="/2015_VSC_Plots/Dunbartonshire WestAberavon_VS2015_pie.png">Dunbartonshire West
<option value="/2015_VSC_Plots/Dundee EastAberavon_VS2015_pie.png">Dundee East
<option value="/2015_VSC_Plots/Dundee WestAberavon_VS2015_pie.png">Dundee West
<option value="/2015_VSC_Plots/Dunfermline & Fife WestAberavon_VS2015_pie.png">Dunfermline & Fife West
<option value="/2015_VSC_Plots/Durham, City OfAberavon_VS2015_pie.png">Durham, City Of"
<option value="/2015_VSC_Plots/Durham NorthAberavon_VS2015_pie.png">Durham North
<option value="/2015_VSC_Plots/Durham North WestAberavon_VS2015_pie.png">Durham North West
<option value="/2015_VSC_Plots/Dwyfor MeirionnyddAberavon_VS2015_pie.png">Dwyfor Meirionnydd
<option value="/2015_VSC_Plots/Ealing Central & ActonAberavon_VS2015_pie.png">Ealing Central & Acton
<option value="/2015_VSC_Plots/Ealing NorthAberavon_VS2015_pie.png">Ealing North
<option value="/2015_VSC_Plots/Ealing SouthallAberavon_VS2015_pie.png">Ealing Southall
<option value="/2015_VSC_Plots/EasingtonAberavon_VS2015_pie.png">Easington
<option value="/2015_VSC_Plots/East HamAberavon_VS2015_pie.png">East Ham
<option value="/2015_VSC_Plots/East Kilbride, Strathaven & LesmahagowAberavon_VS2015_pie.png">East Kilbride, Strathaven & Lesmahagow"
<option value="/2015_VSC_Plots/East LothianAberavon_VS2015_pie.png">East Lothian
<option value="/2015_VSC_Plots/EastbourneAberavon_VS2015_pie.png">Eastbourne
<option value="/2015_VSC_Plots/EastleighAberavon_VS2015_pie.png">Eastleigh
<option value="/2015_VSC_Plots/EddisburyAberavon_VS2015_pie.png">Eddisbury
<option value="/2015_VSC_Plots/Edinburgh EastAberavon_VS2015_pie.png">Edinburgh East
<option value="/2015_VSC_Plots/Edinburgh North & LeithAberavon_VS2015_pie.png">Edinburgh North & Leith
<option value="/2015_VSC_Plots/Edinburgh SouthAberavon_VS2015_pie.png">Edinburgh South
<option value="/2015_VSC_Plots/Edinburgh South WestAberavon_VS2015_pie.png">Edinburgh South West
<option value="/2015_VSC_Plots/Edinburgh WestAberavon_VS2015_pie.png">Edinburgh West
<option value="/2015_VSC_Plots/EdmontonAberavon_VS2015_pie.png">Edmonton
<option value="/2015_VSC_Plots/Ellesmere Port & NestonAberavon_VS2015_pie.png">Ellesmere Port & Neston
<option value="/2015_VSC_Plots/Elmet & RothwellAberavon_VS2015_pie.png">Elmet & Rothwell
<option value="/2015_VSC_Plots/ElthamAberavon_VS2015_pie.png">Eltham
<option value="/2015_VSC_Plots/Enfield NorthAberavon_VS2015_pie.png">Enfield North
<option value="/2015_VSC_Plots/Enfield SouthgateAberavon_VS2015_pie.png">Enfield Southgate
<option value="/2015_VSC_Plots/Epping ForestAberavon_VS2015_pie.png">Epping Forest
<option value="/2015_VSC_Plots/Epsom & EwellAberavon_VS2015_pie.png">Epsom & Ewell
<option value="/2015_VSC_Plots/ErewashAberavon_VS2015_pie.png">Erewash
<option value="/2015_VSC_Plots/Erith & ThamesmeadAberavon_VS2015_pie.png">Erith & Thamesmead
<option value="/2015_VSC_Plots/Esher & WaltonAberavon_VS2015_pie.png">Esher & Walton
<option value="/2015_VSC_Plots/ExeterAberavon_VS2015_pie.png">Exeter
<option value="/2015_VSC_Plots/FalkirkAberavon_VS2015_pie.png">Falkirk
<option value="/2015_VSC_Plots/FarehamAberavon_VS2015_pie.png">Fareham
<option value="/2015_VSC_Plots/Faversham & Kent MidAberavon_VS2015_pie.png">Faversham & Kent Mid
<option value="/2015_VSC_Plots/Feltham & HestonAberavon_VS2015_pie.png">Feltham & Heston
<option value="/2015_VSC_Plots/Fermanagh & South TyroneAberavon_VS2015_pie.png">Fermanagh & South Tyrone
<option value="/2015_VSC_Plots/Fife North EastAberavon_VS2015_pie.png">Fife North East
<option value="/2015_VSC_Plots/Filton & Bradley StokeAberavon_VS2015_pie.png">Filton & Bradley Stoke
<option value="/2015_VSC_Plots/Finchley & Golders GreenAberavon_VS2015_pie.png">Finchley & Golders Green
<option value="/2015_VSC_Plots/Folkestone & HytheAberavon_VS2015_pie.png">Folkestone & Hythe
<option value="/2015_VSC_Plots/Forest Of DeanAberavon_VS2015_pie.png">Forest Of Dean
<option value="/2015_VSC_Plots/FoyleAberavon_VS2015_pie.png">Foyle
<option value="/2015_VSC_Plots/FyldeAberavon_VS2015_pie.png">Fylde
<option value="/2015_VSC_Plots/GainsboroughAberavon_VS2015_pie.png">Gainsborough
<option value="/2015_VSC_Plots/Garston & HalewoodAberavon_VS2015_pie.png">Garston & Halewood
<option value="/2015_VSC_Plots/GatesheadAberavon_VS2015_pie.png">Gateshead
<option value="/2015_VSC_Plots/GedlingAberavon_VS2015_pie.png">Gedling
<option value="/2015_VSC_Plots/Gillingham & RainhamAberavon_VS2015_pie.png">Gillingham & Rainham
<option value="/2015_VSC_Plots/Glasgow CentralAberavon_VS2015_pie.png">Glasgow Central
<option value="/2015_VSC_Plots/Glasgow EastAberavon_VS2015_pie.png">Glasgow East
<option value="/2015_VSC_Plots/Glasgow NorthAberavon_VS2015_pie.png">Glasgow North
<option value="/2015_VSC_Plots/Glasgow North EastAberavon_VS2015_pie.png">Glasgow North East
<option value="/2015_VSC_Plots/Glasgow North WestAberavon_VS2015_pie.png">Glasgow North West
<option value="/2015_VSC_Plots/Glasgow SouthAberavon_VS2015_pie.png">Glasgow South
<option value="/2015_VSC_Plots/Glasgow South WestAberavon_VS2015_pie.png">Glasgow South West
<option value="/2015_VSC_Plots/GlenrothesAberavon_VS2015_pie.png">Glenrothes
<option value="/2015_VSC_Plots/GloucesterAberavon_VS2015_pie.png">Gloucester
<option value="/2015_VSC_Plots/GordonAberavon_VS2015_pie.png">Gordon
<option value="/2015_VSC_Plots/GosportAberavon_VS2015_pie.png">Gosport
<option value="/2015_VSC_Plots/GowerAberavon_VS2015_pie.png">Gower
<option value="/2015_VSC_Plots/Grantham & StamfordAberavon_VS2015_pie.png">Grantham & Stamford
<option value="/2015_VSC_Plots/GraveshamAberavon_VS2015_pie.png">Gravesham
<option value="/2015_VSC_Plots/Great GrimsbyAberavon_VS2015_pie.png">Great Grimsby
<option value="/2015_VSC_Plots/Great YarmouthAberavon_VS2015_pie.png">Great Yarmouth
<option value="/2015_VSC_Plots/Greenwich & WoolwichAberavon_VS2015_pie.png">Greenwich & Woolwich
<option value="/2015_VSC_Plots/GuildfordAberavon_VS2015_pie.png">Guildford
<option value="/2015_VSC_Plots/Hackney North & Stoke NewingtonAberavon_VS2015_pie.png">Hackney North & Stoke Newington
<option value="/2015_VSC_Plots/Hackney South & ShoreditchAberavon_VS2015_pie.png">Hackney South & Shoreditch
<option value="/2015_VSC_Plots/Halesowen & Rowley RegisAberavon_VS2015_pie.png">Halesowen & Rowley Regis
<option value="/2015_VSC_Plots/HalifaxAberavon_VS2015_pie.png">Halifax
<option value="/2015_VSC_Plots/Haltemprice & HowdenAberavon_VS2015_pie.png">Haltemprice & Howden
<option value="/2015_VSC_Plots/HaltonAberavon_VS2015_pie.png">Halton
<option value="/2015_VSC_Plots/HammersmithAberavon_VS2015_pie.png">Hammersmith
<option value="/2015_VSC_Plots/Hampshire EastAberavon_VS2015_pie.png">Hampshire East
<option value="/2015_VSC_Plots/Hampshire North EastAberavon_VS2015_pie.png">Hampshire North East
<option value="/2015_VSC_Plots/Hampshire North WestAberavon_VS2015_pie.png">Hampshire North West
<option value="/2015_VSC_Plots/Hampstead & KilburnAberavon_VS2015_pie.png">Hampstead & Kilburn
<option value="/2015_VSC_Plots/HarboroughAberavon_VS2015_pie.png">Harborough
<option value="/2015_VSC_Plots/HarlowAberavon_VS2015_pie.png">Harlow
<option value="/2015_VSC_Plots/Harrogate & KnaresboroughAberavon_VS2015_pie.png">Harrogate & Knaresborough
<option value="/2015_VSC_Plots/Harrow EastAberavon_VS2015_pie.png">Harrow East
<option value="/2015_VSC_Plots/Harrow WestAberavon_VS2015_pie.png">Harrow West
<option value="/2015_VSC_Plots/HartlepoolAberavon_VS2015_pie.png">Hartlepool
<option value="/2015_VSC_Plots/Harwich & Essex NorthAberavon_VS2015_pie.png">Harwich & Essex North
<option value="/2015_VSC_Plots/Hastings & RyeAberavon_VS2015_pie.png">Hastings & Rye
<option value="/2015_VSC_Plots/HavantAberavon_VS2015_pie.png">Havant
<option value="/2015_VSC_Plots/Hayes & HarlingtonAberavon_VS2015_pie.png">Hayes & Harlington
<option value="/2015_VSC_Plots/Hazel GroveAberavon_VS2015_pie.png">Hazel Grove
<option value="/2015_VSC_Plots/Hemel HempsteadAberavon_VS2015_pie.png">Hemel Hempstead
<option value="/2015_VSC_Plots/HemsworthAberavon_VS2015_pie.png">Hemsworth
<option value="/2015_VSC_Plots/HendonAberavon_VS2015_pie.png">Hendon
<option value="/2015_VSC_Plots/HenleyAberavon_VS2015_pie.png">Henley
<option value="/2015_VSC_Plots/Hereford & Herefordshire SouthAberavon_VS2015_pie.png">Hereford & Herefordshire South
<option value="/2015_VSC_Plots/Herefordshire NorthAberavon_VS2015_pie.png">Herefordshire North
<option value="/2015_VSC_Plots/Hertford & StortfordAberavon_VS2015_pie.png">Hertford & Stortford
<option value="/2015_VSC_Plots/Hertfordshire North EastAberavon_VS2015_pie.png">Hertfordshire North East
<option value="/2015_VSC_Plots/Hertfordshire South WestAberavon_VS2015_pie.png">Hertfordshire South West
<option value="/2015_VSC_Plots/HertsmereAberavon_VS2015_pie.png">Hertsmere
<option value="/2015_VSC_Plots/HexhamAberavon_VS2015_pie.png">Hexham
<option value="/2015_VSC_Plots/Heywood & MiddletonAberavon_VS2015_pie.png">Heywood & Middleton
<option value="/2015_VSC_Plots/High PeakAberavon_VS2015_pie.png">High Peak
<option value="/2015_VSC_Plots/Hitchin & HarpendenAberavon_VS2015_pie.png">Hitchin & Harpenden
<option value="/2015_VSC_Plots/Holborn & St PancrasAberavon_VS2015_pie.png">Holborn & St Pancras
<option value="/2015_VSC_Plots/Hornchurch & UpminsterAberavon_VS2015_pie.png">Hornchurch & Upminster
<option value="/2015_VSC_Plots/Hornsey & Wood GreenAberavon_VS2015_pie.png">Hornsey & Wood Green
<option value="/2015_VSC_Plots/HorshamAberavon_VS2015_pie.png">Horsham
<option value="/2015_VSC_Plots/Houghton & Sunderland SouthAberavon_VS2015_pie.png">Houghton & Sunderland South
<option value="/2015_VSC_Plots/HoveAberavon_VS2015_pie.png">Hove
<option value="/2015_VSC_Plots/HuddersfieldAberavon_VS2015_pie.png">Huddersfield
<option value="/2015_VSC_Plots/Hull EastAberavon_VS2015_pie.png">Hull East
<option value="/2015_VSC_Plots/Hull NorthAberavon_VS2015_pie.png">Hull North
<option value="/2015_VSC_Plots/Hull West & HessleAberavon_VS2015_pie.png">Hull West & Hessle
<option value="/2015_VSC_Plots/HuntingdonAberavon_VS2015_pie.png">Huntingdon
<option value="/2015_VSC_Plots/HyndburnAberavon_VS2015_pie.png">Hyndburn
<option value="/2015_VSC_Plots/Ilford NorthAberavon_VS2015_pie.png">Ilford North
<option value="/2015_VSC_Plots/Ilford SouthAberavon_VS2015_pie.png">Ilford South
<option value="/2015_VSC_Plots/InverclydeAberavon_VS2015_pie.png">Inverclyde
<option value="/2015_VSC_Plots/Inverness, Nairn, Badenoch & StrathspeyAberavon_VS2015_pie.png">Inverness, Nairn, Badenoch & Strathspey"
<option value="/2015_VSC_Plots/IpswichAberavon_VS2015_pie.png">Ipswich
<option value="/2015_VSC_Plots/Isle Of WightAberavon_VS2015_pie.png">Isle Of Wight
<option value="/2015_VSC_Plots/Islington NorthAberavon_VS2015_pie.png">Islington North
<option value="/2015_VSC_Plots/Islington South & FinsburyAberavon_VS2015_pie.png">Islington South & Finsbury
<option value="/2015_VSC_Plots/IslwynAberavon_VS2015_pie.png">Islwyn
<option value="/2015_VSC_Plots/JarrowAberavon_VS2015_pie.png">Jarrow
<option value="/2015_VSC_Plots/KeighleyAberavon_VS2015_pie.png">Keighley
<option value="/2015_VSC_Plots/Kenilworth & SouthamAberavon_VS2015_pie.png">Kenilworth & Southam
<option value="/2015_VSC_Plots/KensingtonAberavon_VS2015_pie.png">Kensington
<option value="/2015_VSC_Plots/KetteringAberavon_VS2015_pie.png">Kettering
<option value="/2015_VSC_Plots/Kilmarnock & LoudounAberavon_VS2015_pie.png">Kilmarnock & Loudoun
<option value="/2015_VSC_Plots/Kingston & SurbitonAberavon_VS2015_pie.png">Kingston & Surbiton
<option value="/2015_VSC_Plots/KingswoodAberavon_VS2015_pie.png">Kingswood
<option value="/2015_VSC_Plots/Kirkcaldy & CowdenbeathAberavon_VS2015_pie.png">Kirkcaldy & Cowdenbeath
<option value="/2015_VSC_Plots/KnowsleyAberavon_VS2015_pie.png">Knowsley
<option value="/2015_VSC_Plots/Lagan ValleyAberavon_VS2015_pie.png">Lagan Valley
<option value="/2015_VSC_Plots/Lanark & Hamilton EastAberavon_VS2015_pie.png">Lanark & Hamilton East
<option value="/2015_VSC_Plots/Lancashire WestAberavon_VS2015_pie.png">Lancashire West
<option value="/2015_VSC_Plots/Lancaster & FleetwoodAberavon_VS2015_pie.png">Lancaster & Fleetwood
<option value="/2015_VSC_Plots/Leeds CentralAberavon_VS2015_pie.png">Leeds Central
<option value="/2015_VSC_Plots/Leeds EastAberavon_VS2015_pie.png">Leeds East
<option value="/2015_VSC_Plots/Leeds North EastAberavon_VS2015_pie.png">Leeds North East
<option value="/2015_VSC_Plots/Leeds North WestAberavon_VS2015_pie.png">Leeds North West
<option value="/2015_VSC_Plots/Leeds WestAberavon_VS2015_pie.png">Leeds West
<option value="/2015_VSC_Plots/Leicester EastAberavon_VS2015_pie.png">Leicester East
<option value="/2015_VSC_Plots/Leicester SouthAberavon_VS2015_pie.png">Leicester South
<option value="/2015_VSC_Plots/Leicester WestAberavon_VS2015_pie.png">Leicester West
<option value="/2015_VSC_Plots/Leicestershire North WestAberavon_VS2015_pie.png">Leicestershire North West
<option value="/2015_VSC_Plots/Leicestershire SouthAberavon_VS2015_pie.png">Leicestershire South
<option value="/2015_VSC_Plots/LeighAberavon_VS2015_pie.png">Leigh
<option value="/2015_VSC_Plots/LewesAberavon_VS2015_pie.png">Lewes
<option value="/2015_VSC_Plots/Lewisham DeptfordAberavon_VS2015_pie.png">Lewisham Deptford
<option value="/2015_VSC_Plots/Lewisham EastAberavon_VS2015_pie.png">Lewisham East
<option value="/2015_VSC_Plots/Lewisham West & PengeAberavon_VS2015_pie.png">Lewisham West & Penge
<option value="/2015_VSC_Plots/Leyton & WansteadAberavon_VS2015_pie.png">Leyton & Wanstead
<option value="/2015_VSC_Plots/LichfieldAberavon_VS2015_pie.png">Lichfield
<option value="/2015_VSC_Plots/LincolnAberavon_VS2015_pie.png">Lincoln
<option value="/2015_VSC_Plots/Linlithgow & Falkirk EastAberavon_VS2015_pie.png">Linlithgow & Falkirk East
<option value="/2015_VSC_Plots/Liverpool RiversideAberavon_VS2015_pie.png">Liverpool Riverside
<option value="/2015_VSC_Plots/Liverpool WaltonAberavon_VS2015_pie.png">Liverpool Walton
<option value="/2015_VSC_Plots/Liverpool WavertreeAberavon_VS2015_pie.png">Liverpool Wavertree
<option value="/2015_VSC_Plots/Liverpool West DerbyAberavon_VS2015_pie.png">Liverpool West Derby
<option value="/2015_VSC_Plots/LivingstonAberavon_VS2015_pie.png">Livingston
<option value="/2015_VSC_Plots/LlanelliAberavon_VS2015_pie.png">Llanelli
<option value="/2015_VSC_Plots/Londonderry EastAberavon_VS2015_pie.png">Londonderry East
<option value="/2015_VSC_Plots/LoughboroughAberavon_VS2015_pie.png">Loughborough
<option value="/2015_VSC_Plots/Louth & HorncastleAberavon_VS2015_pie.png">Louth & Horncastle
<option value="/2015_VSC_Plots/LudlowAberavon_VS2015_pie.png">Ludlow
<option value="/2015_VSC_Plots/Luton NorthAberavon_VS2015_pie.png">Luton North
<option value="/2015_VSC_Plots/Luton SouthAberavon_VS2015_pie.png">Luton South
<option value="/2015_VSC_Plots/MacclesfieldAberavon_VS2015_pie.png">Macclesfield
<option value="/2015_VSC_Plots/MaidenheadAberavon_VS2015_pie.png">Maidenhead
<option value="/2015_VSC_Plots/Maidstone & The WealdAberavon_VS2015_pie.png">Maidstone & The Weald
<option value="/2015_VSC_Plots/MakerfieldAberavon_VS2015_pie.png">Makerfield
<option value="/2015_VSC_Plots/MaldonAberavon_VS2015_pie.png">Maldon
<option value="/2015_VSC_Plots/Manchester CentralAberavon_VS2015_pie.png">Manchester Central
<option value="/2015_VSC_Plots/Manchester GortonAberavon_VS2015_pie.png">Manchester Gorton
<option value="/2015_VSC_Plots/Manchester WithingtonAberavon_VS2015_pie.png">Manchester Withington
<option value="/2015_VSC_Plots/MansfieldAberavon_VS2015_pie.png">Mansfield
<option value="/2015_VSC_Plots/Meon ValleyAberavon_VS2015_pie.png">Meon Valley
<option value="/2015_VSC_Plots/MeridenAberavon_VS2015_pie.png">Meriden
<option value="/2015_VSC_Plots/Merthyr Tydfil & RhymneyAberavon_VS2015_pie.png">Merthyr Tydfil & Rhymney
<option value="/2015_VSC_Plots/MiddlesbroughAberavon_VS2015_pie.png">Middlesbrough
<option value="/2015_VSC_Plots/Middlesbrough South & Cleveland EastAberavon_VS2015_pie.png">Middlesbrough South & Cleveland East
<option value="/2015_VSC_Plots/MidlothianAberavon_VS2015_pie.png">Midlothian
<option value="/2015_VSC_Plots/Milton Keynes NorthAberavon_VS2015_pie.png">Milton Keynes North
<option value="/2015_VSC_Plots/Milton Keynes SouthAberavon_VS2015_pie.png">Milton Keynes South
<option value="/2015_VSC_Plots/Mitcham & MordenAberavon_VS2015_pie.png">Mitcham & Morden
<option value="/2015_VSC_Plots/Mole ValleyAberavon_VS2015_pie.png">Mole Valley
<option value="/2015_VSC_Plots/MonmouthAberavon_VS2015_pie.png">Monmouth
<option value="/2015_VSC_Plots/MontgomeryshireAberavon_VS2015_pie.png">Montgomeryshire
<option value="/2015_VSC_Plots/MorayAberavon_VS2015_pie.png">Moray
<option value="/2015_VSC_Plots/Morecambe & LunesdaleAberavon_VS2015_pie.png">Morecambe & Lunesdale
<option value="/2015_VSC_Plots/Morley & OutwoodAberavon_VS2015_pie.png">Morley & Outwood
<option value="/2015_VSC_Plots/Motherwell & WishawAberavon_VS2015_pie.png">Motherwell & Wishaw
<option value="/2015_VSC_Plots/Na H-Eileanan An IarAberavon_VS2015_pie.png">Na H-Eileanan An Iar
<option value="/2015_VSC_Plots/NeathAberavon_VS2015_pie.png">Neath
<option value="/2015_VSC_Plots/New Forest EastAberavon_VS2015_pie.png">New Forest East
<option value="/2015_VSC_Plots/New Forest WestAberavon_VS2015_pie.png">New Forest West
<option value="/2015_VSC_Plots/NewarkAberavon_VS2015_pie.png">Newark
<option value="/2015_VSC_Plots/NewburyAberavon_VS2015_pie.png">Newbury
<option value="/2015_VSC_Plots/Newcastle-Under-LymeAberavon_VS2015_pie.png">Newcastle-Under-Lyme
<option value="/2015_VSC_Plots/Newcastle Upon Tyne CentralAberavon_VS2015_pie.png">Newcastle Upon Tyne Central
<option value="/2015_VSC_Plots/Newcastle Upon Tyne EastAberavon_VS2015_pie.png">Newcastle Upon Tyne East
<option value="/2015_VSC_Plots/Newcastle Upon Tyne NorthAberavon_VS2015_pie.png">Newcastle Upon Tyne North
<option value="/2015_VSC_Plots/Newport EastAberavon_VS2015_pie.png">Newport East
<option value="/2015_VSC_Plots/Newport WestAberavon_VS2015_pie.png">Newport West
<option value="/2015_VSC_Plots/Newry & ArmaghAberavon_VS2015_pie.png">Newry & Armagh
<option value="/2015_VSC_Plots/Newton AbbotAberavon_VS2015_pie.png">Newton Abbot
<option value="/2015_VSC_Plots/Norfolk MidAberavon_VS2015_pie.png">Norfolk Mid
<option value="/2015_VSC_Plots/Norfolk NorthAberavon_VS2015_pie.png">Norfolk North
<option value="/2015_VSC_Plots/Norfolk North WestAberavon_VS2015_pie.png">Norfolk North West
<option value="/2015_VSC_Plots/Norfolk SouthAberavon_VS2015_pie.png">Norfolk South
<option value="/2015_VSC_Plots/Norfolk South WestAberavon_VS2015_pie.png">Norfolk South West
<option value="/2015_VSC_Plots/Normanton, Pontefract & CastlefordAberavon_VS2015_pie.png">Normanton, Pontefract & Castleford"
<option value="/2015_VSC_Plots/Northampton NorthAberavon_VS2015_pie.png">Northampton North
<option value="/2015_VSC_Plots/Northampton SouthAberavon_VS2015_pie.png">Northampton South
<option value="/2015_VSC_Plots/Northamptonshire SouthAberavon_VS2015_pie.png">Northamptonshire South
<option value="/2015_VSC_Plots/Norwich NorthAberavon_VS2015_pie.png">Norwich North
<option value="/2015_VSC_Plots/Norwich SouthAberavon_VS2015_pie.png">Norwich South
<option value="/2015_VSC_Plots/Nottingham EastAberavon_VS2015_pie.png">Nottingham East
<option value="/2015_VSC_Plots/Nottingham NorthAberavon_VS2015_pie.png">Nottingham North
<option value="/2015_VSC_Plots/Nottingham SouthAberavon_VS2015_pie.png">Nottingham South
<option value="/2015_VSC_Plots/NuneatonAberavon_VS2015_pie.png">Nuneaton
<option value="/2015_VSC_Plots/Ochil & Perthshire SouthAberavon_VS2015_pie.png">Ochil & Perthshire South
<option value="/2015_VSC_Plots/OgmoreAberavon_VS2015_pie.png">Ogmore
<option value="/2015_VSC_Plots/Old Bexley & SidcupAberavon_VS2015_pie.png">Old Bexley & Sidcup
<option value="/2015_VSC_Plots/Oldham East & SaddleworthAberavon_VS2015_pie.png">Oldham East & Saddleworth
<option value="/2015_VSC_Plots/Oldham West & RoytonAberavon_VS2015_pie.png">Oldham West & Royton
<option value="/2015_VSC_Plots/Orkney & ShetlandAberavon_VS2015_pie.png">Orkney & Shetland
<option value="/2015_VSC_Plots/OrpingtonAberavon_VS2015_pie.png">Orpington
<option value="/2015_VSC_Plots/Oxford EastAberavon_VS2015_pie.png">Oxford East
<option value="/2015_VSC_Plots/Oxford West & AbingdonAberavon_VS2015_pie.png">Oxford West & Abingdon
<option value="/2015_VSC_Plots/Paisley & Renfrewshire NorthAberavon_VS2015_pie.png">Paisley & Renfrewshire North
<option value="/2015_VSC_Plots/Paisley & Renfrewshire SouthAberavon_VS2015_pie.png">Paisley & Renfrewshire South
<option value="/2015_VSC_Plots/PendleAberavon_VS2015_pie.png">Pendle
<option value="/2015_VSC_Plots/Penistone & StocksbridgeAberavon_VS2015_pie.png">Penistone & Stocksbridge
<option value="/2015_VSC_Plots/Penrith & The BorderAberavon_VS2015_pie.png">Penrith & The Border
<option value="/2015_VSC_Plots/Perth & Perthshire NorthAberavon_VS2015_pie.png">Perth & Perthshire North
<option value="/2015_VSC_Plots/PeterboroughAberavon_VS2015_pie.png">Peterborough
<option value="/2015_VSC_Plots/Plymouth Moor ViewAberavon_VS2015_pie.png">Plymouth Moor View
<option value="/2015_VSC_Plots/Plymouth Sutton & DevonportAberavon_VS2015_pie.png">Plymouth Sutton & Devonport
<option value="/2015_VSC_Plots/PontypriddAberavon_VS2015_pie.png">Pontypridd
<option value="/2015_VSC_Plots/PooleAberavon_VS2015_pie.png">Poole
<option value="/2015_VSC_Plots/Poplar & LimehouseAberavon_VS2015_pie.png">Poplar & Limehouse
<option value="/2015_VSC_Plots/Portsmouth NorthAberavon_VS2015_pie.png">Portsmouth North
<option value="/2015_VSC_Plots/Portsmouth SouthAberavon_VS2015_pie.png">Portsmouth South
<option value="/2015_VSC_Plots/Preseli PembrokeshireAberavon_VS2015_pie.png">Preseli Pembrokeshire
<option value="/2015_VSC_Plots/PrestonAberavon_VS2015_pie.png">Preston
<option value="/2015_VSC_Plots/PudseyAberavon_VS2015_pie.png">Pudsey
<option value="/2015_VSC_Plots/PutneyAberavon_VS2015_pie.png">Putney
<option value="/2015_VSC_Plots/Rayleigh & WickfordAberavon_VS2015_pie.png">Rayleigh & Wickford
<option value="/2015_VSC_Plots/Reading EastAberavon_VS2015_pie.png">Reading East
<option value="/2015_VSC_Plots/Reading WestAberavon_VS2015_pie.png">Reading West
<option value="/2015_VSC_Plots/RedcarAberavon_VS2015_pie.png">Redcar
<option value="/2015_VSC_Plots/RedditchAberavon_VS2015_pie.png">Redditch
<option value="/2015_VSC_Plots/ReigateAberavon_VS2015_pie.png">Reigate
<option value="/2015_VSC_Plots/Renfrewshire EastAberavon_VS2015_pie.png">Renfrewshire East
<option value="/2015_VSC_Plots/RhonddaAberavon_VS2015_pie.png">Rhondda
<option value="/2015_VSC_Plots/Ribble ValleyAberavon_VS2015_pie.png">Ribble Valley
<option value="/2015_VSC_Plots/Richmond (Yorks)Aberavon_VS2015_pie.png">Richmond (Yorks)
<option value="/2015_VSC_Plots/Richmond ParkAberavon_VS2015_pie.png">Richmond Park
<option value="/2015_VSC_Plots/RochdaleAberavon_VS2015_pie.png">Rochdale
<option value="/2015_VSC_Plots/Rochester & StroodAberavon_VS2015_pie.png">Rochester & Strood
<option value="/2015_VSC_Plots/Rochford & Southend EastAberavon_VS2015_pie.png">Rochford & Southend East
<option value="/2015_VSC_Plots/RomfordAberavon_VS2015_pie.png">Romford
<option value="/2015_VSC_Plots/Romsey & Southampton NorthAberavon_VS2015_pie.png">Romsey & Southampton North
<option value="/2015_VSC_Plots/Ross, Skye & LochaberAberavon_VS2015_pie.png">Ross, Skye & Lochaber"
<option value="/2015_VSC_Plots/Rossendale & DarwenAberavon_VS2015_pie.png">Rossendale & Darwen
<option value="/2015_VSC_Plots/Rother ValleyAberavon_VS2015_pie.png">Rother Valley
<option value="/2015_VSC_Plots/RotherhamAberavon_VS2015_pie.png">Rotherham
<option value="/2015_VSC_Plots/RugbyAberavon_VS2015_pie.png">Rugby
<option value="/2015_VSC_Plots/Ruislip, Northwood & PinnerAberavon_VS2015_pie.png">Ruislip, Northwood & Pinner"
<option value="/2015_VSC_Plots/Runnymede & WeybridgeAberavon_VS2015_pie.png">Runnymede & Weybridge
<option value="/2015_VSC_Plots/RushcliffeAberavon_VS2015_pie.png">Rushcliffe
<option value="/2015_VSC_Plots/Rutherglen & Hamilton WestAberavon_VS2015_pie.png">Rutherglen & Hamilton West
<option value="/2015_VSC_Plots/Rutland & MeltonAberavon_VS2015_pie.png">Rutland & Melton
<option value="/2015_VSC_Plots/Saffron WaldenAberavon_VS2015_pie.png">Saffron Walden
<option value="/2015_VSC_Plots/St AlbansAberavon_VS2015_pie.png">St Albans
<option value="/2015_VSC_Plots/St Austell & NewquayAberavon_VS2015_pie.png">St Austell & Newquay
<option value="/2015_VSC_Plots/St Helens NorthAberavon_VS2015_pie.png">St Helens North
<option value="/2015_VSC_Plots/St Helens South & WhistonAberavon_VS2015_pie.png">St Helens South & Whiston
<option value="/2015_VSC_Plots/St IvesAberavon_VS2015_pie.png">St Ives
<option value="/2015_VSC_Plots/Salford & EcclesAberavon_VS2015_pie.png">Salford & Eccles
<option value="/2015_VSC_Plots/SalisburyAberavon_VS2015_pie.png">Salisbury
<option value="/2015_VSC_Plots/Scarborough & WhitbyAberavon_VS2015_pie.png">Scarborough & Whitby
<option value="/2015_VSC_Plots/ScunthorpeAberavon_VS2015_pie.png">Scunthorpe
<option value="/2015_VSC_Plots/SedgefieldAberavon_VS2015_pie.png">Sedgefield
<option value="/2015_VSC_Plots/Sefton CentralAberavon_VS2015_pie.png">Sefton Central
<option value="/2015_VSC_Plots/Selby & AinstyAberavon_VS2015_pie.png">Selby & Ainsty
<option value="/2015_VSC_Plots/SevenoaksAberavon_VS2015_pie.png">Sevenoaks
<option value="/2015_VSC_Plots/Sheffield Brightside & HillsboroughAberavon_VS2015_pie.png">Sheffield Brightside & Hillsborough
<option value="/2015_VSC_Plots/Sheffield CentralAberavon_VS2015_pie.png">Sheffield Central
<option value="/2015_VSC_Plots/Sheffield HallamAberavon_VS2015_pie.png">Sheffield Hallam
<option value="/2015_VSC_Plots/Sheffield HeeleyAberavon_VS2015_pie.png">Sheffield Heeley
<option value="/2015_VSC_Plots/Sheffield South EastAberavon_VS2015_pie.png">Sheffield South East
<option value="/2015_VSC_Plots/SherwoodAberavon_VS2015_pie.png">Sherwood
<option value="/2015_VSC_Plots/ShipleyAberavon_VS2015_pie.png">Shipley
<option value="/2015_VSC_Plots/Shrewsbury & AtchamAberavon_VS2015_pie.png">Shrewsbury & Atcham
<option value="/2015_VSC_Plots/Shropshire NorthAberavon_VS2015_pie.png">Shropshire North
<option value="/2015_VSC_Plots/Sittingbourne & SheppeyAberavon_VS2015_pie.png">Sittingbourne & Sheppey
<option value="/2015_VSC_Plots/Skipton & RiponAberavon_VS2015_pie.png">Skipton & Ripon
<option value="/2015_VSC_Plots/Sleaford & North HykehamAberavon_VS2015_pie.png">Sleaford & North Hykeham
<option value="/2015_VSC_Plots/SloughAberavon_VS2015_pie.png">Slough
<option value="/2015_VSC_Plots/SolihullAberavon_VS2015_pie.png">Solihull
<option value="/2015_VSC_Plots/Somerset NorthAberavon_VS2015_pie.png">Somerset North
<option value="/2015_VSC_Plots/Somerset North EastAberavon_VS2015_pie.png">Somerset North East
<option value="/2015_VSC_Plots/Somerton & FromeAberavon_VS2015_pie.png">Somerton & Frome
<option value="/2015_VSC_Plots/South Holland & The DeepingsAberavon_VS2015_pie.png">South Holland & The Deepings
<option value="/2015_VSC_Plots/South RibbleAberavon_VS2015_pie.png">South Ribble
<option value="/2015_VSC_Plots/South ShieldsAberavon_VS2015_pie.png">South Shields
<option value="/2015_VSC_Plots/Southampton ItchenAberavon_VS2015_pie.png">Southampton Itchen
<option value="/2015_VSC_Plots/Southampton TestAberavon_VS2015_pie.png">Southampton Test
<option value="/2015_VSC_Plots/Southend WestAberavon_VS2015_pie.png">Southend West
<option value="/2015_VSC_Plots/SouthportAberavon_VS2015_pie.png">Southport
<option value="/2015_VSC_Plots/SpelthorneAberavon_VS2015_pie.png">Spelthorne
<option value="/2015_VSC_Plots/StaffordAberavon_VS2015_pie.png">Stafford
<option value="/2015_VSC_Plots/Staffordshire MoorlandsAberavon_VS2015_pie.png">Staffordshire Moorlands
<option value="/2015_VSC_Plots/Staffordshire SouthAberavon_VS2015_pie.png">Staffordshire South
<option value="/2015_VSC_Plots/Stalybridge & HydeAberavon_VS2015_pie.png">Stalybridge & Hyde
<option value="/2015_VSC_Plots/StevenageAberavon_VS2015_pie.png">Stevenage
<option value="/2015_VSC_Plots/StirlingAberavon_VS2015_pie.png">Stirling
<option value="/2015_VSC_Plots/StockportAberavon_VS2015_pie.png">Stockport
<option value="/2015_VSC_Plots/Stockton NorthAberavon_VS2015_pie.png">Stockton North
<option value="/2015_VSC_Plots/Stockton SouthAberavon_VS2015_pie.png">Stockton South
<option value="/2015_VSC_Plots/Stoke-On-Trent CentralAberavon_VS2015_pie.png">Stoke-On-Trent Central
<option value="/2015_VSC_Plots/Stoke-On-Trent NorthAberavon_VS2015_pie.png">Stoke-On-Trent North
<option value="/2015_VSC_Plots/Stoke-On-Trent SouthAberavon_VS2015_pie.png">Stoke-On-Trent South
<option value="/2015_VSC_Plots/StoneAberavon_VS2015_pie.png">Stone
<option value="/2015_VSC_Plots/StourbridgeAberavon_VS2015_pie.png">Stourbridge
<option value="/2015_VSC_Plots/StrangfordAberavon_VS2015_pie.png">Strangford
<option value="/2015_VSC_Plots/Stratford-On-AvonAberavon_VS2015_pie.png">Stratford-On-Avon
<option value="/2015_VSC_Plots/StreathamAberavon_VS2015_pie.png">Streatham
<option value="/2015_VSC_Plots/Stretford & UrmstonAberavon_VS2015_pie.png">Stretford & Urmston
<option value="/2015_VSC_Plots/StroudAberavon_VS2015_pie.png">Stroud
<option value="/2015_VSC_Plots/Suffolk Central & Ipswich NorthAberavon_VS2015_pie.png">Suffolk Central & Ipswich North
<option value="/2015_VSC_Plots/Suffolk CoastalAberavon_VS2015_pie.png">Suffolk Coastal
<option value="/2015_VSC_Plots/Suffolk SouthAberavon_VS2015_pie.png">Suffolk South
<option value="/2015_VSC_Plots/Suffolk WestAberavon_VS2015_pie.png">Suffolk West
<option value="/2015_VSC_Plots/Sunderland CentralAberavon_VS2015_pie.png">Sunderland Central
<option value="/2015_VSC_Plots/Surrey EastAberavon_VS2015_pie.png">Surrey East
<option value="/2015_VSC_Plots/Surrey HeathAberavon_VS2015_pie.png">Surrey Heath
<option value="/2015_VSC_Plots/Surrey South WestAberavon_VS2015_pie.png">Surrey South West
<option value="/2015_VSC_Plots/Sussex MidAberavon_VS2015_pie.png">Sussex Mid
<option value="/2015_VSC_Plots/Sutton & CheamAberavon_VS2015_pie.png">Sutton & Cheam
<option value="/2015_VSC_Plots/Sutton ColdfieldAberavon_VS2015_pie.png">Sutton Coldfield
<option value="/2015_VSC_Plots/Swansea EastAberavon_VS2015_pie.png">Swansea East
<option value="/2015_VSC_Plots/Swansea WestAberavon_VS2015_pie.png">Swansea West
<option value="/2015_VSC_Plots/Swindon NorthAberavon_VS2015_pie.png">Swindon North
<option value="/2015_VSC_Plots/Swindon SouthAberavon_VS2015_pie.png">Swindon South
<option value="/2015_VSC_Plots/TamworthAberavon_VS2015_pie.png">Tamworth
<option value="/2015_VSC_Plots/TattonAberavon_VS2015_pie.png">Tatton
<option value="/2015_VSC_Plots/Taunton DeaneAberavon_VS2015_pie.png">Taunton Deane
<option value="/2015_VSC_Plots/TelfordAberavon_VS2015_pie.png">Telford
<option value="/2015_VSC_Plots/TewkesburyAberavon_VS2015_pie.png">Tewkesbury
<option value="/2015_VSC_Plots/Thanet NorthAberavon_VS2015_pie.png">Thanet North
<option value="/2015_VSC_Plots/Thanet SouthAberavon_VS2015_pie.png">Thanet South
<option value="/2015_VSC_Plots/Thirsk & MaltonAberavon_VS2015_pie.png">Thirsk & Malton
<option value="/2015_VSC_Plots/Thornbury & YateAberavon_VS2015_pie.png">Thornbury & Yate
<option value="/2015_VSC_Plots/ThurrockAberavon_VS2015_pie.png">Thurrock
<option value="/2015_VSC_Plots/Tiverton & HonitonAberavon_VS2015_pie.png">Tiverton & Honiton
<option value="/2015_VSC_Plots/Tonbridge & MallingAberavon_VS2015_pie.png">Tonbridge & Malling
<option value="/2015_VSC_Plots/TootingAberavon_VS2015_pie.png">Tooting
<option value="/2015_VSC_Plots/TorbayAberavon_VS2015_pie.png">Torbay
<option value="/2015_VSC_Plots/TorfaenAberavon_VS2015_pie.png">Torfaen
<option value="/2015_VSC_Plots/TotnesAberavon_VS2015_pie.png">Totnes
<option value="/2015_VSC_Plots/TottenhamAberavon_VS2015_pie.png">Tottenham
<option value="/2015_VSC_Plots/Truro & FalmouthAberavon_VS2015_pie.png">Truro & Falmouth
<option value="/2015_VSC_Plots/Tunbridge WellsAberavon_VS2015_pie.png">Tunbridge Wells
<option value="/2015_VSC_Plots/TwickenhamAberavon_VS2015_pie.png">Twickenham
<option value="/2015_VSC_Plots/TynemouthAberavon_VS2015_pie.png">Tynemouth
<option value="/2015_VSC_Plots/Tyneside NorthAberavon_VS2015_pie.png">Tyneside North
<option value="/2015_VSC_Plots/Tyrone WestAberavon_VS2015_pie.png">Tyrone West
<option value="/2015_VSC_Plots/Ulster MidAberavon_VS2015_pie.png">Ulster Mid
<option value="/2015_VSC_Plots/Upper BannAberavon_VS2015_pie.png">Upper Bann
<option value="/2015_VSC_Plots/Uxbridge & Ruislip SouthAberavon_VS2015_pie.png">Uxbridge & Ruislip South
<option value="/2015_VSC_Plots/Vale Of ClwydAberavon_VS2015_pie.png">Vale Of Clwyd
<option value="/2015_VSC_Plots/Vale Of GlamorganAberavon_VS2015_pie.png">Vale Of Glamorgan
<option value="/2015_VSC_Plots/VauxhallAberavon_VS2015_pie.png">Vauxhall
<option value="/2015_VSC_Plots/WakefieldAberavon_VS2015_pie.png">Wakefield
<option value="/2015_VSC_Plots/WallaseyAberavon_VS2015_pie.png">Wallasey
<option value="/2015_VSC_Plots/Walsall NorthAberavon_VS2015_pie.png">Walsall North
<option value="/2015_VSC_Plots/Walsall SouthAberavon_VS2015_pie.png">Walsall South
<option value="/2015_VSC_Plots/WalthamstowAberavon_VS2015_pie.png">Walthamstow
<option value="/2015_VSC_Plots/WansbeckAberavon_VS2015_pie.png">Wansbeck
<option value="/2015_VSC_Plots/WantageAberavon_VS2015_pie.png">Wantage
<option value="/2015_VSC_Plots/WarleyAberavon_VS2015_pie.png">Warley
<option value="/2015_VSC_Plots/Warrington NorthAberavon_VS2015_pie.png">Warrington North
<option value="/2015_VSC_Plots/Warrington SouthAberavon_VS2015_pie.png">Warrington South
<option value="/2015_VSC_Plots/Warwick & LeamingtonAberavon_VS2015_pie.png">Warwick & Leamington
<option value="/2015_VSC_Plots/Warwickshire NorthAberavon_VS2015_pie.png">Warwickshire North
<option value="/2015_VSC_Plots/Washington & Sunderland WestAberavon_VS2015_pie.png">Washington & Sunderland West
<option value="/2015_VSC_Plots/WatfordAberavon_VS2015_pie.png">Watford
<option value="/2015_VSC_Plots/WaveneyAberavon_VS2015_pie.png">Waveney
<option value="/2015_VSC_Plots/WealdenAberavon_VS2015_pie.png">Wealden
<option value="/2015_VSC_Plots/Weaver ValeAberavon_VS2015_pie.png">Weaver Vale
<option value="/2015_VSC_Plots/WellingboroughAberavon_VS2015_pie.png">Wellingborough
<option value="/2015_VSC_Plots/WellsAberavon_VS2015_pie.png">Wells
<option value="/2015_VSC_Plots/Welwyn HatfieldAberavon_VS2015_pie.png">Welwyn Hatfield
<option value="/2015_VSC_Plots/Wentworth & DearneAberavon_VS2015_pie.png">Wentworth & Dearne
<option value="/2015_VSC_Plots/West Bromwich EastAberavon_VS2015_pie.png">West Bromwich East
<option value="/2015_VSC_Plots/West Bromwich WestAberavon_VS2015_pie.png">West Bromwich West
<option value="/2015_VSC_Plots/West HamAberavon_VS2015_pie.png">West Ham
<option value="/2015_VSC_Plots/Westminster NorthAberavon_VS2015_pie.png">Westminster North
<option value="/2015_VSC_Plots/Westmorland & LonsdaleAberavon_VS2015_pie.png">Westmorland & Lonsdale
<option value="/2015_VSC_Plots/Weston-Super-MareAberavon_VS2015_pie.png">Weston-Super-Mare
<option value="/2015_VSC_Plots/WiganAberavon_VS2015_pie.png">Wigan
<option value="/2015_VSC_Plots/Wiltshire NorthAberavon_VS2015_pie.png">Wiltshire North
<option value="/2015_VSC_Plots/Wiltshire South WestAberavon_VS2015_pie.png">Wiltshire South West
<option value="/2015_VSC_Plots/WimbledonAberavon_VS2015_pie.png">Wimbledon
<option value="/2015_VSC_Plots/WinchesterAberavon_VS2015_pie.png">Winchester
<option value="/2015_VSC_Plots/WindsorAberavon_VS2015_pie.png">Windsor
<option value="/2015_VSC_Plots/Wirral SouthAberavon_VS2015_pie.png">Wirral South
<option value="/2015_VSC_Plots/Wirral WestAberavon_VS2015_pie.png">Wirral West
<option value="/2015_VSC_Plots/WithamAberavon_VS2015_pie.png">Witham
<option value="/2015_VSC_Plots/WitneyAberavon_VS2015_pie.png">Witney
<option value="/2015_VSC_Plots/WokingAberavon_VS2015_pie.png">Woking
<option value="/2015_VSC_Plots/WokinghamAberavon_VS2015_pie.png">Wokingham
<option value="/2015_VSC_Plots/Wolverhampton North EastAberavon_VS2015_pie.png">Wolverhampton North East
<option value="/2015_VSC_Plots/Wolverhampton South EastAberavon_VS2015_pie.png">Wolverhampton South East
<option value="/2015_VSC_Plots/Wolverhampton South WestAberavon_VS2015_pie.png">Wolverhampton South West
<option value="/2015_VSC_Plots/WorcesterAberavon_VS2015_pie.png">Worcester
<option value="/2015_VSC_Plots/Worcestershire MidAberavon_VS2015_pie.png">Worcestershire Mid
<option value="/2015_VSC_Plots/Worcestershire WestAberavon_VS2015_pie.png">Worcestershire West
<option value="/2015_VSC_Plots/WorkingtonAberavon_VS2015_pie.png">Workington
<option value="/2015_VSC_Plots/Worsley & Eccles SouthAberavon_VS2015_pie.png">Worsley & Eccles South
<option value="/2015_VSC_Plots/Worthing East & ShorehamAberavon_VS2015_pie.png">Worthing East & Shoreham
<option value="/2015_VSC_Plots/Worthing WestAberavon_VS2015_pie.png">Worthing West
<option value="/2015_VSC_Plots/Wrekin, TheAberavon_VS2015_pie.png">Wrekin, The"
<option value="/2015_VSC_Plots/WrexhamAberavon_VS2015_pie.png">Wrexham
<option value="/2015_VSC_Plots/WycombeAberavon_VS2015_pie.png">Wycombe
<option value="/2015_VSC_Plots/Wyre & Preston NorthAberavon_VS2015_pie.png">Wyre & Preston North
<option value="/2015_VSC_Plots/Wyre ForestAberavon_VS2015_pie.png">Wyre Forest
<option value="/2015_VSC_Plots/Wythenshawe & Sale EastAberavon_VS2015_pie.png">Wythenshawe & Sale East
<option value="/2015_VSC_Plots/YeovilAberavon_VS2015_pie.png">Yeovil
<option value="/2015_VSC_Plots/Ynys MonAberavon_VS2015_pie.png">Ynys Mon
<option value="/2015_VSC_Plots/York CentralAberavon_VS2015_pie.png">York Central
<option value="/2015_VSC_Plots/York OuterAberavon_VS2015_pie.png">York Outer
<option value="/2015_VSC_Plots/Yorkshire EastAberavon_VS2015_pie.png">Yorkshire East